
[unstable] # ReCompile `core` and other crates for our custom target
build-std = ["core","compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build] # Custom Target
target = "x86_64-arcane.json"
