
[unstable] # ReCompile `core` and other crates for our custom target
build-std = ["core","compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build] # Custom Target
target = "x86_64-arcane.json"

[target.'cfg(target_os = "none")'] 
# This command links given executable with project's bootloader dependency and then launches QEMU
runner = "bootimage runner"
